[general]
destination = "$HOME/.config/hypr/monitors.conf"

[profiles.desktop]
config_file = "profiles/desktop.conf"
config_file_type = "static"

[[profiles.desktop.conditions.required_monitors]]
description = "Dell Inc. DELL U2722D BNB85P3"
monitor_tag = "left"

[[profiles.desktop.conditions.required_monitors]]
description = "LG Electronics LG ULTRAGEAR+ 308NTBK9U373"
monitor_tag = "middle"

[[profiles.desktop.conditions.required_monitors]]
description = "Dell Inc. DELL U2722D BPB85P3"
monitor_tag = "right"
