[general]
destination = "$HOME/.config/hypr/monitors.conf"

[notifications]
disabled = true

[profiles.default]
config_file = "profiles/default.conf"
config_file_type = "static"
post_apply_exec = "echo 'default' > ~/.config/current_screen_layout && systemctl --user restart waybar"

[[profiles.default.conditions.required_monitors]]
description = ".*"
match_description_using_regex = true

[profiles.framework]
config_file = "profiles/framework.conf"
config_file_type = "static"
post_apply_exec = "echo 'framework' > ~/.config/current_screen_layout && systemctl --user restart waybar"

[[profiles.framework.conditions.required_monitors]]
description = "BOE 0x0BCA"

[profiles.desktop]
config_file = "profiles/desktop.go.tmpl"
config_file_type = "template"
post_apply_exec = "echo 'desktop-all' > ~/.config/current_screen_layout && systemctl --user restart waybar"

[profiles.desktop.static_template_values]
mode = "desktop-all" # or desktop-single

[[profiles.desktop.conditions.required_monitors]]
description = "Dell Inc. DELL U2722D BNB85P3"
monitor_tag = "left"

[[profiles.desktop.conditions.required_monitors]]
description = "LG Electronics LG ULTRAGEAR+ 308NTBK9U373"
monitor_tag = "middle"

[[profiles.desktop.conditions.required_monitors]]
description = "Dell Inc. DELL U2722D BPB85P3"
monitor_tag = "right"
