user-raptor-password: ENC[AES256_GCM,data:fE4CBE7ynz3fF6vWt8+bHf+uX4sZbncwYYsLnKxMU54i/nIeRmtYht0wRAWHMFMtPICQpkEqQ332X03xWmhIeCFOkfOfDzvPmw==,iv:VzGXXrOOtKJOjzWO372JfmajS0iWSKxgJzFDZA428+c=,tag:3PSyyqN3DFMUpDW1kkHD1g==,type:str]
sops:
    age:
        - recipient: age1lv7py8qxw3lgn8980rva0lwz88fsvqfar0szx7yacjxv60cpa3vqgwn7km
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZWpBaDhaTm1wTjdSaHlQ
            dmM4TGc4Z1gyM2VkVEJQQ29HTW5xSUdJcHk0CmdDcVpSdGhhWXJpT29SN0VuUjNx
            Rjh2MXkwMTlNREVicFNHUG5DaUlIZFUKLS0tIDFFWWFHT2lGN1M2OWhJcENFem9x
            c3MzUmlIT1J1bnFCZzRPVS8xZGZ3T2sKHEMDBwES70U5I+H2ImfhaqImDG1LKuLS
            V/A4lM1EleiDvrREnQBHqCDvCi7A2X6oohCNpiLbALF2X99BilO/HA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16k6zekwj3p50kfhzkhwk4dzpj6du6w7twwyzjyvqrqxfy9uxafpqxsa5sm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZelUwQVRYMkRNMytYaGlS
            OWVxNXRxNzNyaUV2dzBBOHYrTjFjaHRuRFQwCitUNkhZeTVCZy9qWVZMS3dYSGRx
            Wkd5eDg1YUJkODlkUjFpTlVLSitLSmcKLS0tIDg1cWZsaFEyVDd5SVAyWm5hYUU0
            ajNUWktzSUVwcUR3T2U0aTVwZjhmR0UKq6ryNuIM2tfLJe+k6k+r1fK1gm9F85zQ
            ucekFSBdUTGmka5s33ukrprGmjRANg08vPtujrr1YlS4JxS1QJ72NA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T10:49:32Z"
    mac: ENC[AES256_GCM,data:BmMX1T4c/eugYS3vPhexCbNXRLdS7udXTUtl9oTZpqAMQxhRCj1y0MnsCgpKVaPH/XYSJS0u8MlImL2MTXqKZ5zj6OLbepptqgcflj2swG/DE1K9L3XD0b/jIwyV2PcNPVSDQWFuK/lNM2edN56dvGlS0DkMWmG+PYxgIGylseY=,iv:qWXv9cV++gmOhlVuL/oDSSm6+VXG0dkrJigRuSXcc8A=,tag:cBGPkxDcmZaqe0xwuS8kbw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
