user-raptor-password: ENC[AES256_GCM,data:+5EGWU0GPLGMyDrDj9DPkHibGrz1/gctLCDFDImYRVBX9wg4VsYQzA6tbgmVSIBFnFs254qP5D348aaFVc+6Qm6PMTEejRysofySjCTCsheaS5rUbSPqbnfdcLrZpaNtVJjr/C0XfXTjWA==,iv:0dINBANR489PG/usQmIzqtN3sHKbjeWQXmTXbvR+fPU=,tag:Sb8QpGSNmYT0Ludv63rI0Q==,type:str]
sops:
    age:
        - recipient: age1yubikey1q27ute0qtans6fqnghlcpngk2k0k0dcgwuzegm36xmvckhm9lqrkguvfwe3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDBPQXJFQSBBNk9lanFq
            blMwNER5WVRUY1FhRXdLMFc2NWplVDNlZVZZRHY5U3pIZHVVSwo5VzRBT0hLMTJS
            bHZ5QmNGL3ZQSVgvTE9DaFltaGhJRW9BWktBblcrbjVFCi0tLSBnWllQcFNDOXBj
            NzNPVHdCcVppZkF3RmVnNHlGQ2NTMk1CY3lXcHZDdWIwCo3iEeDsleAFmtSPBGDp
            vHbqo/p2AlyPjmIYdK1SrP0WSupY6jKTl4r4+GPan2r5ZUPDJ00tSiAHuH5AufoG
            KPA=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T06:44:47Z"
    mac: ENC[AES256_GCM,data:efkKA9EY93E63/8bpTHLwwT5h3X8fbVd5riGw/KvNc9MaxhEoDK+blo1VKTpubNkFk21+02Lt+dF3jz88ugm2Tqtum/FPM5CN5HL+H+q2ehV/Ix8ItVpTMpQ3UONGonI1baUCGYoymjN+7ClEkT0F7PpwQ9nluoGzvalauJ1M0Y=,iv:lYu7P7GNsyXLRRyXBKhdnv8jB0vRjajBwVDg6F48lFg=,tag:ykY/3UpYGoHtCWk6RyATSw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
